# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'mrkolarik'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
#- {name: 'Home & CV', path: 'menu', url: 'index.html'}
#- {name: 'Blog posts', path: 'menu', url: 'writing.html'}
- {name: 'Blog posts', path: 'menu', url: 'blog.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/mrkolarik'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/mrkolarik'}
- {icon: 'globe-americas', link: 'https://scholar.google.cz/citations?user=w6J2MOQAAAAJ&hl=en'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0001-6158-6162'}
#- {icon: 'university', link: 'https://www.vutbr.cz/en/people/martin-kolarik-146862'}
#- {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Blog posts you may enjoy:'

post_date_prefix: 'Written on'
